name: '[Python] Package manifest scan'
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '00 18 * * 1'
jobs:
  python_scan_self:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ministryofjustice/opg-repository-scanner@latest
